# Copyright 2018 IBM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from wwexport import constants

import logging
import datetime
import re
import sys
import argparse
import dateutil
from pathlib import Path

import bleach
from mistletoe import Document, html_renderer
from mistletoe.span_token import SpanToken
import pandas as pd
from babel.dates import format_date, format_datetime, format_time

from jinja2 import Environment, PackageLoader, select_autoescape

logger = logging.getLogger("wwexport")
allowed_tags = ["p", "img"] + bleach.sanitizer.ALLOWED_TAGS


class WWMentionSpan(SpanToken):
    pattern = re.compile(r"\<\@(.+?)\|(.+?)\>")

    def __init__(self, match):
        self.parse_inner = False
        self.id = match.group(1)
        self.display = match.group(2)

class WWSpaceMentionSpan(SpanToken):
    pattern = re.compile(r"\<(\@space)\>")

    def __init__(self, match):
        self.parse_inner = False
        self.display = match.group(1)

class WWImageSpan(SpanToken):
    pattern = re.compile(r"\<\$image\|(.*?)(\|(([0-9])+x([0-9])+))?\>")

    def __init__(self, match):
        self.parse_inner = False
        self.id = match.group(1)
        self.size = match.group(3)
        self.length = match.group(4)
        self.height = match.group(5)

class WWBoldSpan(SpanToken):
    pattern = re.compile(r"\*([^*]+)\*")

    def __init__(self, match):
        self.target = match.group(1)

class WWHTMLRenderer(html_renderer.HTMLRenderer):
    def __init__(self):
        super().__init__(WWMentionSpan, WWSpaceMentionSpan, WWImageSpan, WWBoldSpan)

    def render_ww_mention_span(self, token):
        return "<strong>{name}</strong>".format(name=token.display)

    def render_ww_space_mention_span(self, token):
        return self.render_ww_mention_span(token)

    def render_ww_image_span(self, token):
        return "<img alt='Embedded Image' href='{target}'/>".format(target=token.id)

    def render_ww_bold_span(self, token):
        return "<strong>{inner}</strong>".format(inner=self.render_inner(token))


jinja_env = Environment(
    loader=PackageLoader('wwexport', 'templates'),
    autoescape=select_autoescape(['html', 'xml'])
)


def _jinja_filter_name_case(val: str):
    return val.title() if val is not None and (val.islower() or val.isupper()) else val


def _jinja_filter_md(val: str):
    with WWHTMLRenderer() as renderer:
        return bleach.clean(
            renderer.render(
                Document(val)
            ),
            tags=allowed_tags,
        )


jinja_env.filters["format_date"] = format_date
jinja_env.filters["format_datetime"] = format_datetime
jinja_env.filters["format_time"] = format_time
jinja_env.filters["parse_datetime"] = dateutil.parser.parse
jinja_env.filters["name_case"] = _jinja_filter_name_case
jinja_env.filters["md"] = _jinja_filter_md


def csv_to_html(file: Path, styles: str = "styles.css"):
    logger.info("Converting %s to HTML", file)
    df = pd.read_csv(file, encoding=constants.FILE_ENCODING)
    template = jinja_env.get_template("messages.html")
    with open(file.with_suffix(".html"), "w+") as html_file:
        html_file.write(
            template.render(
                df=df,
                month_year="201811",
                export_date=datetime.datetime.now(),
                styles=styles,
            )
        )


def main(argv):
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Utility to convert from an exported CSV to HTML file")

    parser.add_argument("--file", help="Path to messages CSV file previously generated by the export tool.")
    args = parser.parse_args()

    csv_to_html(Path(args.file))


if __name__ == "__main__":
    main(sys.argv)
